train:
  settings:
    blocks_per_ckpt: 1
    ckpt_intermediate_steps: true
  architecture:
    loss_module:
      diffusion:
        chunk_size: 4

predict:
  settings:
    memory:
      eval:
        # This chunk size is the minimum value, it will be auto-tuned by default
        chunk_size: 4
        offload_inference:
          confidence_heads: true
          token_cutoff: 2800

low_mem:
  settings:
    clear_cache_between_steps: True
    memory:
      eval:
        per_sample_token_cutoff: 0
        per_sample_atom_cutoff: 0
        offload_inference:
          template_module: true
          msa_module: true
          confidence_heads: true
          token_cutoff: 0
